### ISSUE TITLE
go-cron: not found

### ISSUE THREAD

**Issue by atmarammuduli** [eeshugerman/postgres-backup-s3#12]
at line "exec go-cron "$SCHEDULE" /bin/sh backup.sh"

go-cron: not found. how to resolve?

**Comment by eeshugerman** [comment]
Which image tag are you using? And how are you running the container (what command)?

**Comment by atmarammuduli** [comment]
> Which image tag are you using? And how are you running the container (what command)?

I am using latest with following docker-compose.yml. 
Building it from source.  
`docker-compose -f docker-compose.yml up -d --build
`
--docker-compose.yml--
  postgres-backup-s3:
    build:
      context: ./postgres-backup-s3
      dockerfile: Dockerfile
    restart: always
    links:
        - db
    env_file:
        - ./.env.prod.postgres-backup-s3

**Comment by eeshugerman** [comment]
There's no `latest` tag, so I'm not sure what's going on exactly. The image tags available are `10`, `11`, `12`, `13`, and `14`. These are Postgres versions; you should choose the one that matches your Postgres version.

**Comment by atmarammuduli** [comment]
Glad I found my answer. need to add this to Dockerfile

RUN apk add curl
RUN curl -L --insecure https://github.com/odise/go-cron/releases/download/v0.0.6/go-cron-linux.gz | zcat > /usr/local/bin/go-cron
RUN chmod u+x /usr/local/bin/go-cron
RUN apk del curl

so that go-cron is available for the run script
