### ISSUE TITLE
Add BACKUP_KEEP_* options

### ISSUE THREAD

**Issue by fredericoschardong** [eeshugerman/postgres-backup-s3#13]
[This postgres backup image](https://hub.docker.com/r/prodrigestivill/postgres-backup-local) is also based on schickling but stores the backup locally. Nonetheless, a few interesting options are added to improve backup management. They are: 
- BACKUP_KEEP_DAYS Number of daily backups to keep before removal. Defaults to 7. 
- BACKUP_KEEP_WEEKS Number of weekly backups to keep before removal. Defaults to 4. 
- BACKUP_KEEP_MONTHS Number of monthly backups to keep before removal. Defaults to 6. 
- BACKUP_KEEP_MINS Number of minutes for last folder backups to keep before removal. Defaults to 1440.

Is this something you could replicate?

**Comment by eeshugerman** [comment]
We have `BACKUP_KEEP_DAYS` now, thanks @fulminant! I'm gonna go ahead and close this as I'd rather not complicate things with the extra options. Feel free to reopen @fredericoschardong if you strongly object.
