### ISSUE TITLE
Optimize dockerfile

### ISSUE THREAD

**Issue by pratikbin** [eeshugerman/postgres-backup-s3#18]

**Comment by pratikbin** [comment]
https://github.com/eeshugerman/postgres-backup-s3/pull/16

**Comment by eeshugerman** [comment]
> Remove install.sh and embed it into dockerfile.

Why is this better? What are you optimizing for?

**Comment by pratikbin** [comment]
Create less script "files"

**Comment by eeshugerman** [comment]
Sorry, that's not something that I care to optimize for.
