### ISSUE TITLE
Using AWS instance profile

### ISSUE THREAD

**Issue by fred4jupiter** [eeshugerman/postgres-backup-s3#21]
[Feature Request]

Hi eeshugerman,

thanks for this great tool! :-)

It would be great to use an AWS EC2 instance profile where you set the permissions in the IAM role for the instance. This way you don´t need to set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY. The AWS CLI will look for the instance profile when these parameters are not set automatically.

Could you make S3_ACCESS_KEY_ID and S3_SECRET_ACCESS_KEY optional for that?

Best regards,
Michael

**Comment by eeshugerman** [comment]
Done :)
