### ISSUE TITLE
Backups not being deleted

### ISSUE THREAD

**Issue by RicardoViteriR** [eeshugerman/postgres-backup-s3#23]
Hello, I noticed that my backups are not being deleted from S3 - I am using DigitalOcean as it has the same API as Amazon S3. Wondering what may be the issue, my config is as follow:
```
      BACKUP_KEEP_DAYS: '1'
      POSTGRES_DATABASE: postgres
      POSTGRES_HOST: vpn.myhost.com
      POSTGRES_PASSWORD: SECRET
      POSTGRES_PORT: '5433'
      POSTGRES_USER: backups_user
      S3_ACCESS_KEY_ID: SECRET_ID
      S3_BUCKET: AWESOME
      S3_ENDPOINT: https://nyc3.digitaloceanspaces.com
      S3_PREFIX: backup-pg-production
      S3_REGION: nyc3
      S3_SECRET_ACCESS_KEY: /ACCESS
      SCHEDULE: '@every 0h15m0s'
```

**Comment by eeshugerman** [comment]
Hmm 🤔 is there anything in the container logs?

**Comment by RicardoViteriR** [comment]
Everything looks okay from the container log. 

Wondering if the expiration date is set per file or per bucket?

**Comment by eeshugerman** [comment]
Sorry I'm not sure 😕. I didn't implement the auto-removal feature and tbh barely understand the unholy shell incantations it uses. Sometimes I'm tempted to rewrite the whole thing in Python... But please report back if you find a solution!

**Comment by eeshugerman** [comment]
Oh, meant to ask, have you tried with `BACKUP_KEEP_DAYS` > 1? I wonder if it's some kind of edge case.

**Comment by RicardoViteriR** [comment]
@eeshugerman hi, I tested with `BACKUP_KEEP_DAYS > 1` for a few days and it does not erase the file. Unfortunately, I have not looked into it and tinker how to make things work. Wondering if it has anything to do that I am using DigitalOcean as my hosting provider. They are supposed to be S3 compatible.  

Will look into the source code to understand what the logic is to delete files.

**Comment by eeshugerman** [comment]
Well, thanks for trying it!

I use Digital Ocean too, though not with `BACKUP_KEEP_DAYS`. I just enabled it though, will report back with results in a week or so.

**Comment by RicardoViteriR** [comment]
Hi @eeshugerman wondering if you ever go to test this?

**Comment by eeshugerman** [comment]
Hi @RicardoViteriR, I just checked and `BACKUP_KEEP_DAYS: 30` is working as expected for me on DigitalOcean spaces.

**Comment by RicardoViteriR** [comment]
Hi @eeshugerman, I'd like to apologize for opening this issue and not being careful of details. I mistakenly was using another container which has the same configuration options and confused it with yours. I just reran the docker container with your image and deletion worked like a charm.

**Comment by eeshugerman** [comment]
@RicardoViteriR No worries! Thanks for the update.
