### ISSUE TITLE
Support for postgres:15?

### ISSUE THREAD

**Issue by cdelaorden** [eeshugerman/postgres-backup-s3#24]
Hi thanks a lot for this library, very useful (especially the option to backup on demand via command). 

Any chance of generating a tag for version 15 (release ~1 month ago)? It's the latest PG available in Docker but backup fails because of pg_dump version mismatch. 

```
pg_dump: error: server version: 15.1 (Debian 15.1-1.pgdg110+1); pg_dump version: 14.5
pg_dump: error: aborting because of server version mismatch
```

**Comment by eeshugerman** [comment]
Done, https://github.com/eeshugerman/postgres-backup-s3/commit/16df9b3980cb2af232e555972e86a7e23f9fb3b7, `:15` is now available.
