### ISSUE TITLE
postgres 13

### ISSUE THREAD

**Issue by aniketfuryrocks** [eeshugerman/postgres-backup-s3#3]

**Comment by aniketfuryrocks** [comment]
support for postgres version 13 with alpine 3.13

**Comment by eeshugerman** [comment]
Hi, sorry, somehow I missed this notification. I've added support for Postgres v13. I changed how versions are declared, so I handled it and closed your PRs.

**Comment by eeshugerman** [comment]
I haven't actually tested it though, so if you could confirm that it works that would be much appreciated!
