### ISSUE TITLE
Configure multiple schedulers

### ISSUE THREAD

**Issue by oxismailxo** [eeshugerman/postgres-backup-s3#30]
First of all, thank you very much for the great project!

please is it possible to configure multiple schedulers/times?

**Comment by eeshugerman** [comment]
Hi, no, it's not possible to configure multiple schedules. Of course you could run two instances of the container if you don't mind the overhead.

I'm curious what your usecase is? What schedules do you want to use together with the same configuration otherwise?

**Comment by oxismailxo** [comment]
Hello @eeshugerman! yes, I know the two instances trick.

let's say you have a case where you need to configure daily & hourly or daily & monthly schedulers, that's why I asked you about the multiple schedulers. do you think this is logical?

Again thank you for the great project.

**Comment by eeshugerman** [comment]
> let's say you have a case where you need to configure daily & hourly or daily & monthly schedulers, that's why I asked you about the multiple schedulers. do you think this is logical?

If you already have a backup for each hour, why add a backup for each day on top of that? That just gives you two backups for hour 0 and one backup for hours 1-23. Why do you want two backups for hour 0?

**Comment by oxismailxo** [comment]
yes I know that. I need two backups just for the arranging purpose, I will find a way (script, automation, archiving) to copy X(hourly) backup to the daily folder.

thank you @eeshugerman !
