### ISSUE TITLE
Image build error

### ISSUE THREAD

**Issue by next-florinmarica** [eeshugerman/postgres-backup-s3#34]
Hello,
I'm trying to build the image(windows and wsl2 Ubuntu20.04) and I receive this error: 
```
-----
 > [3/7] RUN sh install.sh && rm install.sh:
: not foundstall.sh: line 2:
#0 0.320 install.sh: set: line 3: illegal option -
------
Dockerfile:6
--------------------
   4 |
   5 |     ADD src/install.sh install.sh
   6 | >>> RUN sh install.sh && rm install.sh
   7 |
   8 |     ENV POSTGRES_DATABASE ''
--------------------
ERROR: failed to solve: process "/bin/sh -c sh install.sh && rm install.sh" did not complete successfully: exit code: 2
```

**Comment by eeshugerman** [comment]
I don't have a Windows/WSL box to test on, so I'm not sure I can help you, but I can try. A few questions:
- What command are you using to build the image?
- What version of Docker are you using?
  - Does this version support BuildKit?

**Comment by next-florinmarica** [comment]
I don't know how but I fix the problem, I clone the repository in the wsl and then worked.
Thank you

**Comment by RajMohammed-DeltaX** [comment]
> I don't know how but I fix the problem, I clone the repository in the wsl and then worked. Thank you

Thanks @next-florinmarica  I had also faced the same issue, your reply helped me
