### ISSUE TITLE
No ARM Support

### ISSUE THREAD

**Issue by ikbenignace** [eeshugerman/postgres-backup-s3#35]
Is it possible to add ARM support?

**Comment by eeshugerman** [comment]
I've never tried it out myself, but someone contributed ARM support a while back: https://github.com/eeshugerman/postgres-backup-s3/pull/15

[Docker Hub lists the ARM builds](https://hub.docker.com/r/eeshugerman/postgres-backup-s3/tags), as expected. Are you running into a particular error?

**Comment by petre-c** [comment]
@ikbenignace , I am using this on ARM architecture.
