### ISSUE TITLE
Postgres version 16 support

### ISSUE THREAD

**Issue by gabrielelucci** [eeshugerman/postgres-backup-s3#42]
I successfully restored a backup using `docker.io/eeshugerman/postgres-backup-s3:15` on a container running `docker.io/library/postgres:16-alpine`, so I think it just works? Having official confirmation with a properly tagged image would be great!

**Comment by petre-c** [comment]
Restored, maybe, but when trying to back-up I receive:

```bash
pg_dump: error: aborting because of server version mismatch
pg_dump: detail: server version: 16.1 (Debian 16.1-1.pgdg120+1); pg_dump version: 15.3
```

**Comment by petre-c** [comment]
https://github.com/eeshugerman/postgres-backup-s3/pull/39

**Comment by gabrielelucci** [comment]
Welp, you made me realize I've not been doing backups for two weeks! Luckily, I only updated one project, and looks like the merge request is ready.

**Comment by eeshugerman** [comment]
Done! https://github.com/eeshugerman/postgres-backup-s3/pull/39
