### ISSUE TITLE
SSL validation failed for https://minio.xxx.cn:3000/rvm/backup/rvm_2024-01-19T07%3A56%3A48.dump [SSL: TLSV1_UNRECOGNIZED_NAME] tlsv1 unrecognized name (_ssl.c:1006)

### ISSUE THREAD

**Issue by dreammis** [eeshugerman/postgres-backup-s3#48]
I used self-signatures. minio which is selfhosted.
Let's Encrypt

raise the exception: SSL validation failed for https://minio.xxx.cn:3000/rvm/backup/rvm_2024-01-19T07%3A56%3A48.dump [SSL: TLSV1_UNRECOGNIZED_NAME] tlsv1 unrecognized name (_ssl.c:1006)

how to disable the ssl verify

**Comment by reza-madani** [comment]
I have the same problem
