### ISSUE TITLE
Postgres 14 support please?

### ISSUE THREAD

**Issue by VitaliiTsilnyk** [eeshugerman/postgres-backup-s3#8]
Looks like it's available in the [Alpine 3.15 release](https://alpinelinux.org/posts/Alpine-3.15.0-released.html).

**Comment by eeshugerman** [comment]
:+1:  https://github.com/eeshugerman/postgres-backup-s3/commit/36d5b2888ce34fd075bc7a9f82deab86703e36e2. I haven't tested it, please let me know how it works.
