### ISSUE TITLE
On-demand one-time backup run without the schedule

### ISSUE THREAD

**Issue by VitaliiTsilnyk** [eeshugerman/postgres-backup-s3#9]
The original image [could be](https://github.com/schickling/dockerfiles/blob/master/postgres-backup-s3/run.sh#L10) run without the `SCHEDULE` variable. When doing so it executes one-time backup creation.

When trying to run your version it outputs this instead:
```
WARNING:  is null. Going to sleep.
```

**Comment by eeshugerman** [comment]
Done, see https://github.com/eeshugerman/postgres-backup-s3/commit/8ef632ab84cd6412cea58186296e08044fff33ab. Unfortunately https://github.com/eeshugerman/postgres-backup-s3/issues/10 has become a thing so no build are available until I sort that out.

**Comment by eeshugerman** [comment]
builds are available again

**Comment by YuryHrytsuk** [comment]
@eeshugerman this behavior does not seem to be untuitive. I think the approach with 'RUN_ONCE` ENV from [this repository](https://github.com/kartoza/docker-pg-backup) is more untuitive
